# Taken from https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
---
- name: Add an apt signing key for Kubernetes
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add apt repository for Kubernetes
  become: true
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install kubeadm and kubectl 
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm 
      - kubectl
# TODO: Check to see if Krew is installed lol
- name: Install krew
  shell: |
    set -x; cd "$(mktemp -d)" &&
    OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
    ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" &&
    tar zxvf krew.tar.gz &&
    KREW=./krew-"${OS}_${ARCH}" &&
    "$KREW" install krew
# TODO: Exclude already installed items
- name: Install krew plugins
  command: "kubectl krew install {{ item }}"
  with_items:
    - cert-manager
    - ctx
    - exec-cronjob
    - get-all
    - krew
    - ns
    - pod-dive
    - roll
    - snap
    - tail
    - view-utilization
