---
- name: Clone asdf
  command: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v{{ asdf_version }}
  args:
    creates: ~/.asdf

- name: "source asdf script"
  template:
    src: "asdf.sh.j2"
    dest: "/etc/profile.d/asdf.sh"
    owner: "root"
    group: "root"
    mode: 0755
  become: True

# TODO: This failed when no plugins existed :/
- name: Get installed asdf plugins
  command: "asdf plugin-list"
  register: asdf_plugins
  ignore_errors: yes

- name: Add asdf plugins
  command: "asdf plugin-add {{ item }}"
  when: "item|string not in asdf_plugins.stdout_lines"
  with_items:
    - erlang
    - elixir
    - ruby
    - nodejs
